//
//  Artists.swift
//  hiphop
//
//  Created by 13560793366 on 16/8/10.
//  Copyright © 2016年 13560793366. All rights reserved.
//

import Foundation


public var artistInfoDictionary: Dictionary<String, ArtistItem> = [
    "Afrika Bambaataa": ArtistItem(withChannelName: nil, andChannelID: "UC6S5tOfcFQmZ4lDjnrQwQYg", andGenres: "a", andWikiTitle: "Afrika_Bambaataa"),
    "Afroman":ArtistItem(withChannelName: "AfromanVEVO", andChannelID: nil, andGenres: "a", andWikiTitle: "Afroman"),
    "ASAP Rocky": ArtistItem(withChannelName: "LIVELOVEASAPVEVO", andChannelID: nil, andGenres: "a", andWikiTitle: "ASAP_Rocky"),
    "A Tribe Called Quest":ArtistItem(withChannelName: "TribeCalledQuestVEVO", andChannelID: nil, andGenres: "a", andWikiTitle: "A_Tribe_Called_Quest"),
    "AZ": ArtistItem(withChannelName: "AZVEVO", andChannelID: nil, andGenres: "a", andWikiTitle: "AZ_(rapper)"),
    "Beastie Boys": ArtistItem(withChannelName: "BeastieBoysVEVO", andChannelID: nil, andGenres: "b", andWikiTitle: "Beastie_Boys"),
    "B.o.B": ArtistItem(withChannelName: "bobatl", andChannelID: nil, andGenres: "b", andWikiTitle: "B.o.B"),
    "Biggie": ArtistItem(withChannelName: "BiggieVEVO", andChannelID: nil, andGenres: "b", andWikiTitle: "The_Notorious_B.I.G."),
    "Busta Rhymes": ArtistItem(withChannelName: "BustaRhymesVEVO", andChannelID: nil, andGenres: "b", andWikiTitle: "Busta_Rhymes"),
    "Big L": ArtistItem(withChannelName: "BigLVEVO", andChannelID: nil, andGenres: "b", andWikiTitle: "Big_L"),
    "Black Star": ArtistItem(withChannelName: "BlackStarVEVO", andChannelID: nil, andGenres: "b", andWikiTitle: "Black_Star_(rap_duo)"),
    "Chamillionaire": ArtistItem(withChannelName: "ChamillionaireVEVO", andChannelID: nil, andGenres: "c", andWikiTitle: "Chamillionaire"),
    "Chance the Rapper": ArtistItem(withChannelName: "ChanceThaRapper", andChannelID: nil, andGenres: "c", andWikiTitle: "Chance_the_Rapper"),
    "Chief Keef": ArtistItem(withChannelName: "GLOGangRecords1017", andChannelID: nil, andGenres: "c", andWikiTitle: "Chief_Keef"),
    "Clipping.":ArtistItem(withChannelName: nil, andChannelID: "UCIahymQzVz4bXn1DrDB3gtg",andGenres: "c", andWikiTitle: "Clipping."),
    "Common":ArtistItem(withChannelName: "CommonVEVO", andChannelID: nil, andGenres: "c", andWikiTitle: "Common_(rapper)"),
    "De La Soul":ArtistItem(withChannelName: "DeLaSolarSystem", andChannelID: nil, andGenres: "d", andWikiTitle: "De_La_Soul"),
    "Death Grips":ArtistItem(withChannelName: "deathgrippin", andChannelID: nil, andGenres: "d", andWikiTitle: "Death_Grips"),
    "DMX":ArtistItem(withChannelName: "DMXVEVO", andChannelID: nil, andGenres: "d", andWikiTitle: "DMX_(rapper)"),
    "Drake": ArtistItem(withChannelName: "DrakeVEVO", andChannelID: nil, andGenres: "d", andWikiTitle: "Drake_(musician)"),
    "Dr. Dre": ArtistItem(withChannelName: "DrDreVEVO", andChannelID: nil, andGenres: "d", andWikiTitle: "Dr._Dre"),
    "Eazy-E":ArtistItem(withChannelName: "EazyEVEVO", andChannelID: nil, andGenres: "e", andWikiTitle: "Eazy-E"),
    "Eminem": ArtistItem(withChannelName: "EminemVEVO", andChannelID: nil, andGenres: "e", andWikiTitle: "Eminem"),
    "Eric B. & Rakim": ArtistItem(withChannelName: "EricBAndRakimVEVO", andChannelID: nil, andGenres: "e", andWikiTitle: "Eric_B._%26_Rakim"),
    "E-40":ArtistItem(withChannelName: "E40TV", andChannelID: nil, andGenres: "e", andWikiTitle: "E-40"),
    "Fetty Wap":ArtistItem(withChannelName: "harlemfetty", andChannelID: nil, andGenres: "f", andWikiTitle: "Fetty_Wap"),
    "Flo Rida": ArtistItem(withChannelName: "officialflo", andChannelID: nil, andGenres: "f", andWikiTitle: "Flo_Rida"),
    "Fort Minor": ArtistItem(withChannelName: "FortMinorVideos", andChannelID: nil, andGenres: "f", andWikiTitle: "Fort_Minor"),
    "Frank Ocean":ArtistItem(withChannelName: "FrankOceanVEVO", andChannelID: nil, andGenres: "f", andWikiTitle: "Frank_Ocean"),
    "Fugees":ArtistItem(withChannelName: "TheFugeesVEVO", andChannelID: nil, andGenres: "f", andWikiTitle: "Fugees"),
    "Future": ArtistItem(withChannelName: "FutureVEVO", andChannelID: nil, andGenres: "f", andWikiTitle: "Future_(rapper)"),
    "Gang Starr":ArtistItem(withChannelName: nil, andChannelID: "UCPN9k1RTnz3OxA3t8Dc5lCQ", andGenres: "g", andWikiTitle: "Gang_Starr"),
    "Grandmaster Flash":ArtistItem(withChannelName: "djgrandmasterflash", andChannelID: nil, andGenres: "g", andWikiTitle: "Grandmaster_Flash"),
    "Gucci Mane":ArtistItem(withChannelName: "OfficialGucciMane", andChannelID: nil, andGenres: "g", andWikiTitle: "Gucci_Mane"),
    "Guru":ArtistItem(withChannelName: nil, andChannelID: "UCeZVYymjpCOu26-xRJLtjEA", andGenres: "g", andWikiTitle: "Guru_(rapper)"),
    "MC Hammer": ArtistItem(withChannelName: "MCHammerVevo", andChannelID: nil, andGenres: "h", andWikiTitle: "MC_Hammer"),
    "Hopsin": ArtistItem(withChannelName: "Hopsintv", andChannelID: nil, andGenres: "h", andWikiTitle: "Hopsin"),
    "Ice Cube": ArtistItem(withChannelName: "IceCubeVEVO", andChannelID: nil, andGenres: "i", andWikiTitle: "Ice_Cube"),
    "Immortal Technique": ArtistItem(withChannelName: nil, andChannelID: "UCYWdn8GKtpvhc0DmcTQjG_w", andGenres: "i", andWikiTitle: "Immortal_Technique"),
    "Jay Z": ArtistItem(withChannelName: "JayZVEVO", andChannelID: nil, andGenres: "j", andWikiTitle: "Jay_Z"),
    "J. cole": ArtistItem(withChannelName: "JColeVEVO", andChannelID: nil, andGenres: "j", andWikiTitle: "J._Cole"),
    "J Dilla": ArtistItem(withChannelName: nil, andChannelID: "UCg6G23d_0Rdx3W5XbxC7N8A", andGenres: "j", andWikiTitle: "J_Dilla"),
    "Juicy J": ArtistItem(withChannelName: "TheJuicyJVEVO", andChannelID: nil, andGenres: "j", andWikiTitle: "Juicy_J"),
    "Kanye west": ArtistItem(withChannelName: "KanyeWestVEVO", andChannelID: nil, andGenres: "k", andWikiTitle: "Kanye_West"),
    "Kendrick Lamar": ArtistItem(withChannelName: "KendrickLamarVEVO", andChannelID: nil, andGenres: "k", andWikiTitle: "Kendrick_Lamar"),
    "DJ Khaled": ArtistItem(withChannelName: "DJKhaledVEVO", andChannelID: nil, andGenres: "k", andWikiTitle: "DJ_Khaled"),
    "Kool G Rap": ArtistItem(withChannelName: "KoolGRapVEVO", andChannelID: nil, andGenres: "k", andWikiTitle: "Kool_G_Rap"),
    "DJ Kool Herc": ArtistItem(withChannelName: nil, andChannelID: "UCIbIJFS1zaZxf-1deAM5mXQ", andGenres: "k", andWikiTitle: "DJ_Kool_Herc"),
    "KRS-One": ArtistItem(withChannelName: "KRSOneVEVO", andChannelID: nil, andGenres: "k", andWikiTitle: "KRS-One"),
    "Lil Wayne": ArtistItem(withChannelName: "YMWayneCarter", andChannelID: nil, andGenres: "l", andWikiTitle: "Lil_Wayne"),
    "Ludacris": ArtistItem(withChannelName: "LudacrisVEVO", andChannelID: nil, andGenres: "l", andWikiTitle: "Ludacris"),
    "LL Cool J": ArtistItem(withChannelName: "LLCoolJVEVO", andChannelID: nil, andGenres: "l", andWikiTitle: "LL_Cool_J"),
    "Lupe Fiasco": ArtistItem(withChannelName: "LupeFiasco", andChannelID: nil, andGenres: "l", andWikiTitle: "Lupe_Fiasco"),
    "Macklemore & Ryan Lewis": ArtistItem(withChannelName: "RyanLewisProductions", andChannelID: nil, andGenres: "m", andWikiTitle: "Macklemore_%26_Ryan_Lewis"),
    "Madvillain": ArtistItem(withChannelName: nil, andChannelID: "UCvYD4mt2SEikFlX0iJmTKvw", andGenres: "Alternative hip hop, Jazz rap", andWikiTitle: "Madvillain"),
    "Method Man": ArtistItem(withChannelName: "MethodManVEVO", andChannelID: nil, andGenres: "Hardcore hip hop, East Coast hip hop", andWikiTitle: "Method_Man"),
    "Missy Elliott": ArtistItem(withChannelName: nil, andChannelID: "UC_u0CLjE2CglTTAS_WX-zCg", andGenres: "m", andWikiTitle: "Missy_Elliott"),
    "Mobb Deep": ArtistItem(withChannelName: "MobbDeepVEVO", andChannelID: nil, andGenres: "East Coast hip hop, Hardcore hip hop, Gangsta rap", andWikiTitle: "Mobb_Deep"),
    "Mos Def": ArtistItem(withChannelName: "MosDefVEVO", andChannelID: nil, andGenres: "m", andWikiTitle: "Mos_Def"),
    "Nas": ArtistItem(withChannelName: "NasVEVO", andChannelID: nil, andGenres: "n", andWikiTitle: "Nas"),
    "Naughty by Nature": ArtistItem(withChannelName: "naughtybynature", andChannelID: nil, andGenres: "East Coast hip hop", andWikiTitle: "Naughty_by_Nature"),
    "N*E*R*D": ArtistItem(withChannelName: "NERDVEVO", andChannelID: nil, andGenres: "Alternative hip hop", andWikiTitle: "N.E.R.D"),
    "Nicki Minaj": ArtistItem(withChannelName: "NickiMinajAtVEVO", andChannelID: nil, andGenres: "Pop Rap", andWikiTitle: "Nicki_Minaj"),
    "N.W.A": ArtistItem(withChannelName: nil, andChannelID: "UCZ4DZXWEzXbeUgHv1-MTvEg", andGenres:"West Coast hip hop, Gangsta rap", andWikiTitle: "N.W.A"),
    "OutKast": ArtistItem(withChannelName: "OutkastVEVO", andChannelID: nil, andGenres: "o", andWikiTitle: "Outkast"),
    "Pitbull": ArtistItem(withChannelName: "PitbullVEVO", andChannelID: nil, andGenres: "Pop Rap", andWikiTitle: "Pitbull_(rapper)"),
    "DJ Premier": ArtistItem(withChannelName: "Premierwuzhere", andChannelID: nil, andGenres: "p", andWikiTitle: "DJ_Premier"),
    "Public Enemy": ArtistItem(withChannelName: "PublicEnemyVEVO", andChannelID: nil, andGenres: "p", andWikiTitle: "Public_Enemy_(band)"),
    "Puff Daddy": ArtistItem(withChannelName: "PuffDaddyVEVO", andChannelID: nil, andGenres: "p", andWikiTitle: "Sean_Combs"),
    "Q-Tip": ArtistItem(withChannelName: "QTipVEVO", andChannelID: nil, andGenres: "q", andWikiTitle: "Q-Tip_(musician)"),
    "Rakim": ArtistItem(withChannelName: nil, andChannelID: "UCFMS1sbij1WaZzZpnBDCs3A", andGenres: "", andWikiTitle: "Rakim"),
    "MC Ren": ArtistItem(withChannelName: nil, andChannelID: "UCYycuLgD0x-UZB7Bm7l8pYw", andGenres: "r", andWikiTitle: "MC_Ren"),
    "Rick Ross": ArtistItem(withChannelName: "RickRossVEVO", andChannelID: nil, andGenres: "r", andWikiTitle: "Rick_Ross"),
    "Run–D.M.C.": ArtistItem(withChannelName: "RUNDMCVEVO", andChannelID: nil, andGenres: "r", andWikiTitle: "Run–D.M.C."),
    "Salt-N-Pepa": ArtistItem(withChannelName: "SaltNPepaVEVO", andChannelID: nil, andGenres: "s", andWikiTitle: "Salt-N-Pepa"),
    "Scarface": ArtistItem(withChannelName: nil, andChannelID: "UC9v3AUfaYiap8vPHN5lyOYQ", andGenres: "s", andWikiTitle: "Scarface_(rapper)"),
    "DJ Shadow": ArtistItem(withChannelName: "DJShadowVEVO", andChannelID: nil, andGenres: "Instrumental hip hop, Trip hop, Turntablism", andWikiTitle: "DJ_Shadow"),
    "Shabazz Palaces": ArtistItem(withChannelName: nil, andChannelID: "UC-gsojD53RpKVFvxNVdQiWA", andGenres: "Alternative hip hop, Experimental hip hop", andWikiTitle: "Shabazz_Palaces"),
    "Snoop Dogg": ArtistItem(withChannelName: "SnoopDoggVEVO", andChannelID: nil, andGenres: "s", andWikiTitle: "Snoop_Dogg"),
    "Tech N9ne": ArtistItem(withChannelName: "TechN9neVEVO", andChannelID: nil, andGenres: "t", andWikiTitle: "Tech_N9ne"),
    "The Game": ArtistItem(withChannelName: "TheGameVEVO", andChannelID: nil, andGenres: "t", andWikiTitle: "The_Game_(rapper)"),
    "The lonely island": ArtistItem(withChannelName: "thelonelyisland", andChannelID: nil, andGenres: "Alternative hip hop, Comedy hip hop", andWikiTitle: "The_Lonely_Island"),
    "The Pharcyde": ArtistItem(withChannelName: nil, andChannelID: "UCPBVpB_roy80QRKWi4vwRVQ", andGenres: "Alternative hip hop", andWikiTitle: "The_Pharcyde"),
    "The Roots": ArtistItem(withChannelName: "TheRootsVEVO", andChannelID: nil, andGenres: "Jazz Rap", andWikiTitle: "The_Roots"),
    "The Sugarhill Gang": ArtistItem(withChannelName: nil, andChannelID: "UCU0JJCdCVXuFY0wlwn4iYDg", andGenres: "Old-school hip hop", andWikiTitle: "The_Sugarhill_Gang"),
    "Three 6 mafia": ArtistItem(withChannelName: "Three6MafiaVEVO", andChannelID: nil, andGenres: "t", andWikiTitle: "Three_6_Mafia"),
    "T.I.": ArtistItem(withChannelName: "TIVEVO", andChannelID: nil, andGenres: "Trap rap, Gangsta rap, Southern hip hop", andWikiTitle: "T.I."),
    "Vanilla Ice": ArtistItem(withChannelName: "officialvanillaice", andChannelID: nil, andGenres: "Pop Rap", andWikiTitle: "Vanilla_Ice"),
    "Waka Flocka Flame": ArtistItem(withChannelName: "wakaflocka1017", andChannelID: nil, andGenres: "w", andWikiTitle: "Waka_Flocka_Flame"),
    "Warren G": ArtistItem(withChannelName: "WarrenGVEVO", andChannelID: nil, andGenres: "w", andWikiTitle: "Warren_G"),
    "Wiz Khalifa": ArtistItem(withChannelName: "taylorgangent", andChannelID: nil, andGenres: "w", andWikiTitle: "Wiz_Khalifa"),
    "Wu-tang Clan": ArtistItem(withChannelName: "WuTangClanVEVO", andChannelID: nil, andGenres: "Hardcore hip hop, East Coast Hip Hop", andWikiTitle: "Wu-Tang_Clan"),
    "Yelawolf": ArtistItem(withChannelName: "YelawolfVEVO", andChannelID: nil, andGenres: "y", andWikiTitle: "Yelawolf"),
    "Yo Gotti": ArtistItem(withChannelName: "yogottiVEVO", andChannelID: nil, andGenres: "y", andWikiTitle: "Yo_Gotti"),
    "Young Jeezy": ArtistItem(withChannelName: "YoungJeezyVEVO", andChannelID: nil, andGenres: "y", andWikiTitle: "Young_Jeezy"),
    "Young Thug": ArtistItem(withChannelName: "YoungThugOnline", andChannelID: nil, andGenres: "u", andWikiTitle: "Young_Thug"),
    "2 Chainz": ArtistItem(withChannelName: "2ChainzVEVO", andChannelID: nil, andGenres: "#", andWikiTitle: "2_Chainz"),
    "2pac": ArtistItem(withChannelName: "2PacVEVO", andChannelID: nil, andGenres: "#", andWikiTitle: "Tupac_Shakur"),
    "50cent": ArtistItem(withChannelName: "50CentVEVO", andChannelID: nil, andGenres: "#", andWikiTitle: "50_Cent"),
    //"": ArtistItem(withChannelName: <#T##String?#>, andChannelID: <#T##String?#>, andGenres: <#T##String#>, andWikiTitle: <#T##String#>),
    
]
